name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install ttt
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Install pytest other dependencies
      run: pip install pytest pytest-xdist pytest-cov setuptools
    - name: Run examples with pytest
      run: pytest -n auto tests/test.py --durations=0 -v --cov
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}