name: test2

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-tests2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-xdist pytest-cov
    - name: Run tests with pytest and coverage
      run: |
        pytest -n auto tests/test2.py --durations=0 -v --cov=ttt --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true